### ISSUE TITLE
any idea about parallelising in Distributed memory system

### ISSUE THREAD

**Issue by sukesh93** [fletcher/c-sss#6]
hi fletcher,
Can you trigger some ideas for implementing of SSS in Distributed memory

**Comment by fletcher** [comment]
What would your goal be for doing this?  (I am not familiar with distributed memory, beyond just googling it.)

Typically SSS would be used on short strings of text.  If you need to encrypt a larger file, the best way is probably to encrypt the file using a more traditional method with a password, and use SSS to divide the password into shares.  So there's not much need to use parallel processing for performance reasons that I'm aware of.

**Comment by sukesh93** [comment]
to increase the speed of generating the secrets and recombining of them..

**Comment by fletcher** [comment]
But that's my point.  On my 5-6 year old Mac Mini, the speed of doing this is basically instantaneous with smaller numbers of shares (0.001s, which is the smallest unit of measurement in the tool I used).  So while I suppose there may be some room to improve this on a percentage basis, the practical difference between 0.001s and even 0.000s is negligible unless one is sequentially processing millions of secrets....

Even bumping to a requirement of 254 out of 255 shares takes less than 0.2 seconds to generate on the same machine.  I suppose there may be practical use cases for this config, it seems unlikely.  Cutting this to 90 out of 100 shares improves the time down to 0.02 seconds.

Only you would know whether you really need performance faster than this, but it seems unlikely in real world uses. I also wonder whether the overhead of parallelizing this would offset any benefits you might see -- you could theoretically perform the modular exponentiation for each share separately and then add all the coefficients back together at the end.  But it's not clear to me that this would result in a significant performance gain.

Perhaps if you describe your use case further I could help, but otherwise that's all I've got.
